/* The following code was generated by JFlex 1.7.0 */

//lexico
/*1. paquete de importaciones*/
package Analizadores;
import java_cup.runtime.Symbol;
import Errores.Excepcion;
import java.util.ArrayList; //para errores
import Token.TokenInfo;



/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>src/Analizadores/Scanner.jflex</tt>
 */
public class scanner implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\1\1\20\1\23\1\23\1\22\22\0\1\1\1\31\1\17"+
    "\2\0\1\70\1\27\1\24\1\57\1\60\1\26\1\66\1\63\1\67"+
    "\1\3\1\25\12\2\1\56\1\55\1\35\1\33\1\34\2\0\1\11"+
    "\1\43\1\45\1\41\1\7\1\10\1\44\1\46\1\37\1\15\1\53"+
    "\1\12\1\50\1\40\1\42\1\54\1\15\1\5\1\16\1\4\1\6"+
    "\1\47\1\51\3\15\1\64\1\21\1\65\1\32\1\14\1\0\1\11"+
    "\1\43\1\45\1\41\1\7\1\10\1\44\1\46\1\37\1\15\1\53"+
    "\1\12\1\50\1\40\1\42\1\54\1\15\1\5\1\16\1\4\1\6"+
    "\1\47\1\51\3\15\1\62\1\30\1\61\7\0\1\23\252\0\2\36"+
    "\115\0\1\13\u1ea8\0\1\23\1\23\u0100\0\1\52\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udee5\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\7\5\1\1\1\6"+
    "\1\5\1\1\1\7\1\1\1\10\1\11\2\1\1\12"+
    "\1\13\1\14\1\15\1\16\1\1\11\5\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\1\25\1\26\1\27\1\30"+
    "\1\31\1\32\1\0\6\5\1\0\4\5\1\0\1\5"+
    "\2\0\1\5\1\0\1\33\2\0\1\2\1\0\1\34"+
    "\1\35\1\36\1\37\1\40\1\41\1\42\1\43\1\44"+
    "\1\0\1\44\2\5\1\45\11\5\1\46\1\47\1\50"+
    "\1\5\1\0\4\5\1\0\2\5\1\0\1\5\1\51"+
    "\2\5\1\0\1\5\2\0\2\5\1\52\1\2\1\0"+
    "\2\53\1\54\5\5\1\55\1\0\2\5\1\0\1\5"+
    "\1\0\1\5\1\56\1\0\4\5\2\57\1\0\1\5"+
    "\2\60\2\5\2\61\3\0\5\5\1\62\1\5\1\0"+
    "\1\5\1\63\2\64\1\5\1\0\1\5\1\0\1\5"+
    "\1\0\3\5\1\65\2\66\2\5\3\0\4\5\2\67"+
    "\1\0\1\5\2\70\1\71\2\72\1\0\1\5\1\0"+
    "\1\5\1\73\1\74\1\75\1\76\1\77\1\100\1\0"+
    "\1\77\1\100\1\5\1\101\1\0\1\5\1\0\1\5"+
    "\1\0\1\5\1\0\1\5\1\0\1\5\2\102\2\103"+
    "\1\0\1\5\2\104\1\0\1\5\2\105";

  private static int [] zzUnpackAction() {
    int [] result = new int[235];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\71\0\162\0\253\0\71\0\344\0\u011d\0\u0156"+
    "\0\u018f\0\u01c8\0\u0201\0\u023a\0\u0273\0\u02ac\0\u02e5\0\u031e"+
    "\0\71\0\u0357\0\u0390\0\u03c9\0\u0402\0\u043b\0\u0474\0\71"+
    "\0\u04ad\0\u04e6\0\u051f\0\u0558\0\u0591\0\u05ca\0\u0603\0\u063c"+
    "\0\u0675\0\u06ae\0\u06e7\0\u0720\0\u0759\0\71\0\71\0\71"+
    "\0\71\0\71\0\71\0\71\0\71\0\71\0\u0792\0\u07cb"+
    "\0\71\0\u0804\0\u083d\0\u0876\0\u08af\0\u08e8\0\u0921\0\u095a"+
    "\0\u0993\0\u09cc\0\u0a05\0\u0a3e\0\u0a77\0\u0ab0\0\u0ae9\0\u0b22"+
    "\0\u02ac\0\u0b5b\0\u031e\0\71\0\u0b94\0\u0bcd\0\u0c06\0\u0c3f"+
    "\0\71\0\71\0\71\0\71\0\71\0\71\0\71\0\71"+
    "\0\71\0\u0c78\0\u0156\0\u0cb1\0\u0cea\0\u0d23\0\u0d5c\0\u0d95"+
    "\0\u0dce\0\u0e07\0\u0e40\0\u0e79\0\u0eb2\0\u0eeb\0\u0f24\0\71"+
    "\0\71\0\u0804\0\u0f5d\0\u0f96\0\u0fcf\0\u1008\0\u1041\0\u107a"+
    "\0\u10b3\0\u10ec\0\u1125\0\u115e\0\u1197\0\u0156\0\u11d0\0\u1209"+
    "\0\u1242\0\u127b\0\u12b4\0\u12ed\0\u1326\0\u135f\0\71\0\71"+
    "\0\u1398\0\71\0\u0156\0\u0156\0\u13d1\0\u140a\0\u1443\0\u147c"+
    "\0\u14b5\0\u0156\0\u14ee\0\u1527\0\u1560\0\u1599\0\u15d2\0\u160b"+
    "\0\u1644\0\u0156\0\u167d\0\u16b6\0\u16ef\0\u1728\0\u1761\0\71"+
    "\0\u0156\0\u179a\0\u17d3\0\71\0\u0156\0\u180c\0\u1845\0\71"+
    "\0\u0156\0\u187e\0\u18b7\0\u18f0\0\u1929\0\u1962\0\u199b\0\u19d4"+
    "\0\u1a0d\0\u0156\0\u1a46\0\u1a7f\0\u1ab8\0\u0156\0\71\0\u0156"+
    "\0\u1af1\0\u1b2a\0\u1b63\0\u1b9c\0\u1bd5\0\u1c0e\0\u1c47\0\u1c80"+
    "\0\u1cb9\0\u0156\0\71\0\u0156\0\u1cf2\0\u1d2b\0\u1d64\0\u1d9d"+
    "\0\u1dd6\0\u1e0f\0\u1e48\0\u1e81\0\u1eba\0\71\0\u0156\0\u1ef3"+
    "\0\u1f2c\0\71\0\u0156\0\u0156\0\71\0\u0156\0\u1f65\0\u1f9e"+
    "\0\u1fd7\0\u2010\0\u0156\0\u0156\0\u0156\0\u0156\0\71\0\71"+
    "\0\u2049\0\u0156\0\u0156\0\u2082\0\u0156\0\u20bb\0\u20f4\0\u212d"+
    "\0\u2166\0\u219f\0\u21d8\0\u2211\0\u224a\0\u2283\0\u22bc\0\71"+
    "\0\u0156\0\71\0\u0156\0\u22f5\0\u232e\0\71\0\u0156\0\u2367"+
    "\0\u23a0\0\71\0\u0156";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[235];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\10\1\17\1\20"+
    "\1\21\1\2\1\3\1\0\1\22\1\23\1\24\1\25"+
    "\1\26\1\27\1\30\1\31\1\32\1\33\1\34\1\35"+
    "\1\36\1\37\1\10\1\40\1\10\1\41\1\10\1\42"+
    "\1\43\1\44\1\2\1\10\1\45\1\46\1\47\1\50"+
    "\1\51\1\52\1\53\1\54\1\55\1\56\1\57\1\60"+
    "\1\61\72\0\1\3\20\0\1\3\50\0\1\4\1\62"+
    "\67\0\1\10\1\0\1\10\1\63\5\10\1\0\3\10"+
    "\20\0\3\10\1\64\7\10\1\0\2\10\16\0\1\10"+
    "\1\0\3\10\1\65\3\10\1\0\3\10\20\0\3\10"+
    "\1\66\7\10\1\0\2\10\16\0\1\10\1\0\7\10"+
    "\1\0\3\10\20\0\13\10\1\0\2\10\16\0\1\10"+
    "\1\0\6\10\1\67\1\0\3\10\20\0\13\10\1\0"+
    "\2\10\16\0\1\10\1\0\5\10\1\70\1\10\1\0"+
    "\3\10\17\0\1\71\1\72\2\10\1\73\7\10\1\0"+
    "\2\10\16\0\1\10\1\0\7\10\1\0\3\10\20\0"+
    "\13\10\1\0\1\10\1\74\16\0\1\10\1\0\3\10"+
    "\1\75\3\10\1\0\3\10\17\0\1\76\1\77\12\10"+
    "\1\0\2\10\20\0\1\100\70\0\7\10\1\0\1\101"+
    "\2\10\20\0\13\10\1\0\2\10\16\0\1\10\1\0"+
    "\1\102\6\10\1\0\3\10\20\0\13\10\1\0\2\10"+
    "\14\0\17\103\1\104\1\0\1\105\47\103\24\106\1\0"+
    "\44\106\25\0\1\107\1\110\70\0\1\111\71\0\1\112"+
    "\71\0\1\113\73\0\1\114\70\0\1\115\1\116\67\0"+
    "\1\117\70\0\1\120\45\0\1\121\27\0\1\122\32\0"+
    "\1\10\1\0\4\10\1\123\2\10\1\0\3\10\20\0"+
    "\1\10\1\124\11\10\1\0\2\10\16\0\1\10\1\0"+
    "\3\10\1\125\3\10\1\0\3\10\20\0\13\10\1\0"+
    "\2\10\16\0\1\10\1\0\7\10\1\0\3\10\20\0"+
    "\3\10\1\126\7\10\1\0\2\10\16\0\1\10\1\0"+
    "\1\10\1\127\5\10\1\0\3\10\20\0\3\10\1\130"+
    "\7\10\1\0\2\10\16\0\1\10\1\0\7\10\1\0"+
    "\3\10\20\0\3\10\1\131\3\10\1\132\3\10\1\0"+
    "\2\10\16\0\1\10\1\0\5\10\1\133\1\10\1\0"+
    "\3\10\20\0\3\10\1\134\7\10\1\0\2\10\16\0"+
    "\1\10\1\0\5\10\1\135\1\10\1\0\3\10\20\0"+
    "\13\10\1\0\2\10\16\0\1\10\1\0\7\10\1\0"+
    "\3\10\20\0\7\10\1\136\3\10\1\0\2\10\16\0"+
    "\1\10\1\0\1\10\1\137\5\10\1\0\3\10\20\0"+
    "\13\10\1\0\2\10\102\0\1\140\71\0\1\141\3\0"+
    "\1\142\70\0\1\10\1\0\2\10\1\143\4\10\1\0"+
    "\3\10\20\0\13\10\1\0\2\10\16\0\1\10\1\0"+
    "\7\10\1\144\2\10\1\145\20\0\13\10\1\0\2\10"+
    "\16\0\1\10\1\0\1\146\6\10\1\0\3\10\20\0"+
    "\11\10\1\147\1\10\1\0\2\10\16\0\1\10\1\0"+
    "\2\10\1\150\4\10\1\0\3\10\20\0\13\10\1\0"+
    "\2\10\16\0\1\10\1\0\7\10\1\151\2\10\1\152"+
    "\20\0\13\10\1\0\2\10\16\0\1\10\1\0\6\10"+
    "\1\153\1\0\3\10\20\0\13\10\1\0\2\10\54\0"+
    "\1\154\32\0\1\10\1\0\7\10\1\0\3\10\20\0"+
    "\1\10\1\155\11\10\1\0\2\10\16\0\1\10\1\0"+
    "\1\10\1\156\5\10\1\0\3\10\20\0\13\10\1\0"+
    "\2\10\16\0\1\10\1\0\7\10\1\0\3\10\20\0"+
    "\13\10\1\0\1\10\1\157\16\0\1\10\1\0\7\10"+
    "\1\0\3\10\20\0\1\10\1\160\11\10\1\0\2\10"+
    "\27\0\1\161\2\0\1\161\54\0\1\10\1\0\7\10"+
    "\1\161\2\10\1\162\20\0\13\10\1\0\2\10\21\0"+
    "\1\163\3\0\1\164\61\0\1\10\1\0\1\10\1\165"+
    "\3\10\1\166\1\10\1\0\3\10\20\0\13\10\1\0"+
    "\2\10\14\0\20\103\1\0\1\103\2\0\45\103\24\0"+
    "\1\167\44\0\20\107\1\170\1\107\1\170\46\107\26\110"+
    "\1\171\42\110\4\0\1\172\66\0\1\10\1\0\1\173"+
    "\6\10\1\0\3\10\20\0\13\10\1\0\2\10\16\0"+
    "\1\10\1\0\7\10\1\0\3\10\20\0\12\10\1\174"+
    "\1\0\2\10\16\0\1\10\1\0\2\10\1\175\4\10"+
    "\1\0\3\10\20\0\13\10\1\0\2\10\16\0\1\10"+
    "\1\0\3\10\1\176\3\10\1\0\3\10\20\0\13\10"+
    "\1\0\2\10\16\0\1\10\1\0\7\10\1\0\3\10"+
    "\20\0\3\10\1\177\7\10\1\0\2\10\16\0\1\10"+
    "\1\0\7\10\1\0\3\10\20\0\1\10\1\200\11\10"+
    "\1\0\2\10\16\0\1\10\1\0\5\10\1\201\1\10"+
    "\1\0\3\10\20\0\13\10\1\0\2\10\16\0\1\10"+
    "\1\0\1\10\1\202\5\10\1\0\3\10\20\0\13\10"+
    "\1\0\2\10\16\0\1\10\1\0\7\10\1\0\3\10"+
    "\17\0\1\203\1\204\12\10\1\0\2\10\16\0\1\10"+
    "\1\0\1\205\6\10\1\0\3\10\20\0\13\10\1\0"+
    "\2\10\16\0\1\10\1\0\7\10\1\0\3\10\17\0"+
    "\1\206\1\207\12\10\1\0\2\10\16\0\1\10\1\0"+
    "\7\10\1\0\3\10\17\0\1\210\1\211\12\10\1\0"+
    "\2\10\16\0\1\10\1\0\3\10\1\212\3\10\1\0"+
    "\3\10\20\0\13\10\1\0\2\10\20\0\1\213\66\0"+
    "\1\10\1\0\1\214\6\10\1\0\3\10\20\0\13\10"+
    "\1\0\2\10\16\0\1\10\1\0\2\10\1\215\4\10"+
    "\1\0\3\10\20\0\13\10\1\0\2\10\16\0\1\10"+
    "\1\0\7\10\1\0\3\10\20\0\3\10\1\216\7\10"+
    "\1\0\2\10\16\0\1\10\1\0\7\10\1\0\3\10"+
    "\20\0\1\10\1\217\11\10\1\0\2\10\23\0\1\220"+
    "\63\0\1\10\1\0\3\10\1\221\3\10\1\0\3\10"+
    "\20\0\13\10\1\0\2\10\16\0\1\10\1\0\7\10"+
    "\1\222\2\10\1\223\20\0\13\10\1\0\2\10\55\0"+
    "\1\224\31\0\1\10\1\0\7\10\1\0\3\10\20\0"+
    "\2\10\1\225\10\10\1\0\2\10\16\0\1\10\1\0"+
    "\3\10\1\226\3\10\1\0\3\10\20\0\13\10\1\0"+
    "\2\10\16\0\1\10\1\0\7\10\1\0\3\10\20\0"+
    "\5\10\1\227\5\10\1\0\2\10\20\0\1\230\66\0"+
    "\1\10\1\0\1\231\6\10\1\0\3\10\20\0\13\10"+
    "\1\0\2\10\22\0\1\232\27\0\2\233\36\0\1\234"+
    "\65\0\1\10\1\0\2\10\1\235\4\10\1\0\3\10"+
    "\17\0\1\233\1\236\12\10\1\0\2\10\16\0\1\10"+
    "\1\0\1\10\1\237\5\10\1\0\3\10\20\0\13\10"+
    "\1\0\2\10\14\0\25\110\1\170\1\171\42\110\2\0"+
    "\1\10\1\0\7\10\1\0\3\10\20\0\4\10\1\240"+
    "\6\10\1\0\2\10\16\0\1\10\1\0\5\10\1\241"+
    "\1\10\1\0\3\10\20\0\13\10\1\0\2\10\16\0"+
    "\1\10\1\0\6\10\1\242\1\0\3\10\20\0\13\10"+
    "\1\0\2\10\16\0\1\10\1\0\1\243\6\10\1\244"+
    "\2\10\1\245\20\0\13\10\1\0\2\10\16\0\1\10"+
    "\1\0\1\10\1\246\5\10\1\0\3\10\20\0\13\10"+
    "\1\0\2\10\55\0\1\247\31\0\1\10\1\0\7\10"+
    "\1\0\3\10\20\0\2\10\1\250\10\10\1\0\2\10"+
    "\16\0\1\10\1\0\7\10\1\0\3\10\20\0\6\10"+
    "\1\251\4\10\1\0\2\10\26\0\1\252\60\0\1\10"+
    "\1\0\6\10\1\253\1\0\3\10\20\0\13\10\1\0"+
    "\2\10\54\0\1\254\32\0\1\10\1\0\7\10\1\0"+
    "\3\10\20\0\1\10\1\255\11\10\1\0\2\10\21\0"+
    "\1\256\65\0\1\10\1\0\1\10\1\257\5\10\1\0"+
    "\3\10\20\0\13\10\1\0\2\10\16\0\1\10\1\0"+
    "\1\10\1\260\5\10\1\0\3\10\20\0\13\10\1\0"+
    "\2\10\16\0\1\10\1\0\7\10\1\0\3\10\20\0"+
    "\10\10\1\261\2\10\1\0\2\10\16\0\1\10\1\0"+
    "\7\10\1\0\3\10\20\0\2\10\1\262\10\10\1\0"+
    "\2\10\23\0\1\263\63\0\1\10\1\0\3\10\1\264"+
    "\3\10\1\0\3\10\20\0\13\10\1\0\2\10\16\0"+
    "\1\10\1\0\7\10\1\0\3\10\20\0\1\10\1\265"+
    "\11\10\1\0\2\10\16\0\1\10\1\0\1\266\6\10"+
    "\1\0\3\10\20\0\13\10\1\0\2\10\61\0\1\267"+
    "\63\0\1\270\34\0\1\271\66\0\1\10\1\0\7\10"+
    "\1\0\3\10\20\0\6\10\1\272\4\10\1\0\2\10"+
    "\16\0\1\10\1\0\7\10\1\0\3\10\20\0\1\10"+
    "\1\273\11\10\1\0\2\10\16\0\1\10\1\0\1\274"+
    "\6\10\1\0\3\10\20\0\13\10\1\0\2\10\16\0"+
    "\1\10\1\0\6\10\1\275\1\0\3\10\20\0\13\10"+
    "\1\0\2\10\16\0\1\10\1\0\7\10\1\0\3\10"+
    "\20\0\13\10\1\276\1\277\1\10\16\0\1\10\1\0"+
    "\7\10\1\0\3\10\17\0\1\300\1\301\12\10\1\0"+
    "\2\10\20\0\1\302\66\0\1\10\1\0\1\303\6\10"+
    "\1\0\3\10\20\0\13\10\1\0\2\10\16\0\1\10"+
    "\1\0\7\10\1\0\3\10\20\0\7\10\1\304\3\10"+
    "\1\0\2\10\23\0\1\305\63\0\1\10\1\0\3\10"+
    "\1\306\3\10\1\0\3\10\20\0\13\10\1\0\2\10"+
    "\20\0\1\307\66\0\1\10\1\0\1\310\6\10\1\0"+
    "\3\10\20\0\13\10\1\0\2\10\52\0\2\311\33\0"+
    "\1\10\1\0\7\10\1\0\3\10\17\0\1\311\1\312"+
    "\12\10\1\0\2\10\16\0\1\10\1\0\7\10\1\0"+
    "\3\10\20\0\1\10\1\313\11\10\1\0\2\10\16\0"+
    "\1\10\1\0\3\10\1\314\3\10\1\0\3\10\20\0"+
    "\13\10\1\0\2\10\16\0\1\10\1\0\7\10\1\0"+
    "\3\10\20\0\2\10\1\315\10\10\1\0\2\10\16\0"+
    "\1\10\1\0\7\10\1\0\3\10\20\0\7\10\1\316"+
    "\3\10\1\0\2\10\20\0\1\317\130\0\1\320\40\0"+
    "\1\321\56\0\1\10\1\0\1\322\6\10\1\0\3\10"+
    "\20\0\13\10\1\0\2\10\16\0\1\10\1\0\7\10"+
    "\1\0\3\10\20\0\5\10\1\323\5\10\1\0\2\10"+
    "\16\0\1\10\1\0\7\10\1\0\1\324\2\10\20\0"+
    "\13\10\1\0\2\10\16\0\1\10\1\0\3\10\1\325"+
    "\3\10\1\0\3\10\20\0\13\10\1\0\2\10\54\0"+
    "\1\326\32\0\1\10\1\0\7\10\1\0\3\10\20\0"+
    "\1\10\1\327\11\10\1\0\2\10\26\0\1\330\60\0"+
    "\1\10\1\0\6\10\1\331\1\0\3\10\20\0\13\10"+
    "\1\0\2\10\54\0\1\332\32\0\1\10\1\0\7\10"+
    "\1\0\3\10\20\0\1\10\1\333\11\10\1\0\2\10"+
    "\65\0\1\334\21\0\1\10\1\0\7\10\1\0\3\10"+
    "\20\0\12\10\1\335\1\0\2\10\22\0\1\336\64\0"+
    "\1\10\1\0\2\10\1\337\4\10\1\0\3\10\20\0"+
    "\13\10\1\0\2\10\54\0\1\340\32\0\1\10\1\0"+
    "\7\10\1\0\3\10\20\0\1\10\1\341\11\10\1\0"+
    "\2\10\60\0\1\342\26\0\1\10\1\0\7\10\1\0"+
    "\3\10\20\0\5\10\1\343\5\10\1\0\2\10\52\0"+
    "\2\344\33\0\1\10\1\0\7\10\1\0\3\10\17\0"+
    "\1\344\1\345\12\10\1\0\2\10\23\0\1\346\63\0"+
    "\1\10\1\0\3\10\1\347\3\10\1\0\3\10\20\0"+
    "\13\10\1\0\2\10\20\0\1\350\66\0\1\10\1\0"+
    "\1\351\6\10\1\0\3\10\20\0\13\10\1\0\2\10"+
    "\62\0\1\352\24\0\1\10\1\0\7\10\1\0\3\10"+
    "\20\0\7\10\1\353\3\10\1\0\2\10\14\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[9177];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\2\1\1\11\13\1\1\11\6\1\1\11"+
    "\15\1\11\11\2\1\1\11\1\0\6\1\1\0\4\1"+
    "\1\0\1\1\2\0\1\1\1\0\1\11\2\0\1\1"+
    "\1\0\11\11\1\0\15\1\2\11\2\1\1\0\4\1"+
    "\1\0\2\1\1\0\4\1\1\0\1\1\2\0\2\1"+
    "\2\11\1\0\1\11\10\1\1\0\2\1\1\0\1\1"+
    "\1\0\2\1\1\0\4\1\1\11\1\1\1\0\1\1"+
    "\1\11\3\1\1\11\1\1\3\0\7\1\1\0\2\1"+
    "\1\11\2\1\1\0\1\1\1\0\1\1\1\0\4\1"+
    "\1\11\3\1\3\0\4\1\1\11\1\1\1\0\1\1"+
    "\1\11\2\1\1\11\1\1\1\0\1\1\1\0\5\1"+
    "\2\11\1\0\4\1\1\0\1\1\1\0\1\1\1\0"+
    "\1\1\1\0\1\1\1\0\1\1\1\11\1\1\1\11"+
    "\1\1\1\0\1\1\1\11\1\1\1\0\1\1\1\11"+
    "\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[235];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    //codigo de usuario, clases , variables objetos, arreglos
    public ArrayList<Excepcion> Errores = new ArrayList();

    // Lista para almacenar los tokens
    private ArrayList<TokenInfo> tokens = new ArrayList<>();

    // Método para obtener la lista de tokens
    public ArrayList<TokenInfo> getTokens() {
        return tokens;
    }

    //



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public scanner(java.io.Reader in) {
      yyline = 1;
    yychar = 1;
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 228) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { //guarda los errores lexicos
    Errores.add(new Excepcion("Lexico","Caracter no valido: "+ yytext(), yyline, yychar));
            } 
            // fall through
          case 70: break;
          case 2: 
            { 
            } 
            // fall through
          case 71: break;
          case 3: 
            { TokenInfo token = new TokenInfo(yytext(), "ENTERO", yyline, yychar); tokens.add(token);return new Symbol(sym.ENTERO,yyline,yychar,yytext());
            } 
            // fall through
          case 72: break;
          case 4: 
            { TokenInfo token = new TokenInfo(yytext(), "PUNTO", yyline, yychar);  tokens.add(token); return new Symbol(sym.PUNTO,yyline,yychar, yytext());
            } 
            // fall through
          case 73: break;
          case 5: 
            { TokenInfo token = new TokenInfo(yytext(), "ID", yyline, yychar); tokens.add(token); return new Symbol(sym.ID,yyline,yychar,yytext());
            } 
            // fall through
          case 74: break;
          case 6: 
            { TokenInfo token = new TokenInfo(yytext(), "DEFAULT", yyline, yychar);  tokens.add(token); return new Symbol(sym.DEFAULT,yyline,yychar, yytext());
            } 
            // fall through
          case 75: break;
          case 7: 
            { yychar=1;
            } 
            // fall through
          case 76: break;
          case 8: 
            { TokenInfo token = new TokenInfo(yytext(), "DIV", yyline, yychar); tokens.add(token); return new Symbol(sym.DIV, yyline, yychar, yytext());
            } 
            // fall through
          case 77: break;
          case 9: 
            { TokenInfo token = new TokenInfo(yytext(), "POR", yyline, yychar); tokens.add(token); return new Symbol(sym.POR, yyline, yychar, yytext());
            } 
            // fall through
          case 78: break;
          case 10: 
            { TokenInfo token = new TokenInfo(yytext(), "NOT", yyline, yychar);  tokens.add(token); return new Symbol(sym.NOT, yyline, yychar, yytext());
            } 
            // fall through
          case 79: break;
          case 11: 
            { TokenInfo token = new TokenInfo(yytext(), "XOR", yyline, yychar);  tokens.add(token); return new Symbol(sym.XOR, yyline, yychar, yytext());
            } 
            // fall through
          case 80: break;
          case 12: 
            { TokenInfo token = new TokenInfo(yytext(), "IGUAL", yyline, yychar);  tokens.add(token); return new Symbol(sym.IGUAL,yyline,yychar, yytext());
            } 
            // fall through
          case 81: break;
          case 13: 
            { TokenInfo token = new TokenInfo(yytext(), "MAYOR", yyline, yychar);  tokens.add(token); return new Symbol(sym.MAYOR, yyline, yychar, yytext());
            } 
            // fall through
          case 82: break;
          case 14: 
            { TokenInfo token = new TokenInfo(yytext(), "MENOR", yyline, yychar);  tokens.add(token); return new Symbol(sym.MENOR, yyline, yychar, yytext());
            } 
            // fall through
          case 83: break;
          case 15: 
            { TokenInfo token = new TokenInfo(yytext(), "PT_COMA", yyline, yychar); tokens.add(token); return new Symbol(sym.PT_COMA,yyline,yychar, yytext());
            } 
            // fall through
          case 84: break;
          case 16: 
            { TokenInfo token = new TokenInfo(yytext(), "DOS_PT", yyline, yychar);  tokens.add(token); return new Symbol(sym.DOS_PT,yyline,yychar, yytext());
            } 
            // fall through
          case 85: break;
          case 17: 
            { TokenInfo token = new TokenInfo(yytext(), "PAR_IZQ", yyline, yychar);  tokens.add(token); return new Symbol(sym.PAR_IZQ,yyline,yychar, yytext());
            } 
            // fall through
          case 86: break;
          case 18: 
            { TokenInfo token = new TokenInfo(yytext(), "PAR_DER", yyline, yychar);  tokens.add(token); return new Symbol(sym.PAR_DER,yyline,yychar, yytext());
            } 
            // fall through
          case 87: break;
          case 19: 
            { TokenInfo token = new TokenInfo(yytext(), "LLAV_DER", yyline, yychar);  tokens.add(token); return new Symbol(sym.LLAV_DER,yyline,yychar, yytext());
            } 
            // fall through
          case 88: break;
          case 20: 
            { TokenInfo token = new TokenInfo(yytext(), "LLAV_IZQ", yyline, yychar);  tokens.add(token); return new Symbol(sym.LLAV_IZQ,yyline,yychar, yytext());
            } 
            // fall through
          case 89: break;
          case 21: 
            { TokenInfo token = new TokenInfo(yytext(), "COMA", yyline, yychar);  tokens.add(token); return new Symbol(sym.COMA,yyline,yychar, yytext());
            } 
            // fall through
          case 90: break;
          case 22: 
            { TokenInfo token = new TokenInfo(yytext(), "COR_IZQ", yyline, yychar);  tokens.add(token); return new Symbol(sym.COR_IZQ,yyline,yychar, yytext());
            } 
            // fall through
          case 91: break;
          case 23: 
            { TokenInfo token = new TokenInfo(yytext(), "COR_DER", yyline, yychar);  tokens.add(token); return new Symbol(sym.COR_DER,yyline,yychar, yytext());
            } 
            // fall through
          case 92: break;
          case 24: 
            { TokenInfo token = new TokenInfo(yytext(), "MAS", yyline, yychar); tokens.add(token); return new Symbol(sym.MAS, yyline, yychar, yytext());
            } 
            // fall through
          case 93: break;
          case 25: 
            { TokenInfo token = new TokenInfo(yytext(), "MENOS", yyline, yychar); tokens.add(token); return new Symbol(sym.MENOS, yyline, yychar, yytext());
            } 
            // fall through
          case 94: break;
          case 26: 
            { TokenInfo token = new TokenInfo(yytext(), "MOD", yyline, yychar); tokens.add(token); return new Symbol(sym.MOD, yyline, yychar, yytext());
            } 
            // fall through
          case 95: break;
          case 27: 
            { String cadena = yytext();
    cadena = cadena.substring(1, cadena.length()-1);
    TokenInfo token = new TokenInfo(cadena, "CADENA", yyline, yychar);
    tokens.add(token);
    return new Symbol(sym.CADENA, yyline, yychar, cadena);
            } 
            // fall through
          case 96: break;
          case 28: 
            { TokenInfo token = new TokenInfo(yytext(), "POTENCIA", yyline, yychar); tokens.add(token); return new Symbol(sym.POTENCIA, yyline, yychar, yytext());
            } 
            // fall through
          case 97: break;
          case 29: 
            { TokenInfo token = new TokenInfo(yytext(), "AND", yyline, yychar);  tokens.add(token); return new Symbol(sym.AND, yyline, yychar, yytext());
            } 
            // fall through
          case 98: break;
          case 30: 
            { TokenInfo token = new TokenInfo(yytext(), "OR", yyline, yychar);  tokens.add(token); return new Symbol(sym.OR, yyline, yychar, yytext());
            } 
            // fall through
          case 99: break;
          case 31: 
            { TokenInfo token = new TokenInfo(yytext(), "DISTINTO", yyline, yychar);  tokens.add(token); return new Symbol(sym.DISTINTO, yyline, yychar, yytext());
            } 
            // fall through
          case 100: break;
          case 32: 
            { TokenInfo token = new TokenInfo(yytext(), "IGUALIGUAL", yyline, yychar);  tokens.add(token); return new Symbol(sym.IGUALIGUAL, yyline, yychar, yytext());
            } 
            // fall through
          case 101: break;
          case 33: 
            { TokenInfo token = new TokenInfo(yytext(), "CASE", yyline, yychar);  tokens.add(token); return new Symbol(sym.CASE,yyline,yychar, yytext());
            } 
            // fall through
          case 102: break;
          case 34: 
            { TokenInfo token = new TokenInfo(yytext(), "MAYORIGUAL", yyline, yychar);  tokens.add(token); return new Symbol(sym.MAYORIGUAL, yyline, yychar, yytext());
            } 
            // fall through
          case 103: break;
          case 35: 
            { TokenInfo token = new TokenInfo(yytext(), "MENORIGUAL", yyline, yychar);  tokens.add(token); return new Symbol(sym.MENORIGUAL, yyline, yychar, yytext());
            } 
            // fall through
          case 104: break;
          case 36: 
            { TokenInfo token = new TokenInfo(yytext(), "IF", yyline, yychar); tokens.add(token); return new Symbol(sym.IF,yyline,yychar,yytext());
            } 
            // fall through
          case 105: break;
          case 37: 
            { TokenInfo token = new TokenInfo(yytext(), "DO", yyline, yychar);  tokens.add(token); return new Symbol(sym.DO,yyline,yychar,yytext());
            } 
            // fall through
          case 106: break;
          case 38: 
            { TokenInfo token = new TokenInfo(yytext(), "INC", yyline, yychar); tokens.add(token); return new Symbol(sym.INC, yyline, yychar, yytext());
            } 
            // fall through
          case 107: break;
          case 39: 
            { TokenInfo token = new TokenInfo(yytext(), "DEC", yyline, yychar); tokens.add(token); return new Symbol(sym.DEC, yyline, yychar, yytext());
            } 
            // fall through
          case 108: break;
          case 40: 
            { TokenInfo token = new TokenInfo(yytext(), "DECIMAL", yyline, yychar); tokens.add(token);return new Symbol(sym.DECIMAL,yyline,yychar,yytext());
            } 
            // fall through
          case 109: break;
          case 41: 
            { TokenInfo token = new TokenInfo(yytext(), "FOR", yyline, yychar);  tokens.add(token); return new Symbol(sym.FOR,yyline,yychar,yytext());
            } 
            // fall through
          case 110: break;
          case 42: 
            { String caracter = yytext();
    caracter = caracter.substring(1, caracter.length()-1);
    TokenInfo token = new TokenInfo(caracter, "CARACTER", yyline, yychar);
    tokens.add(token);
    return new Symbol(sym.CARACTER, yyline, yychar, caracter);
            } 
            // fall through
          case 111: break;
          case 43: 
            { TokenInfo token = new TokenInfo(yytext(), "INT", yyline, yychar);  tokens.add(token); return new Symbol(sym.INT,yyline,yychar,yytext());
            } 
            // fall through
          case 112: break;
          case 44: 
            { TokenInfo token = new TokenInfo(yytext(), "NEW", yyline, yychar);  tokens.add(token); return new Symbol(sym.NEW,yyline,yychar,yytext());
            } 
            // fall through
          case 113: break;
          case 45: 
            { TokenInfo token = new TokenInfo(yytext(), "VAR", yyline, yychar);  tokens.add(token); return new Symbol(sym.VAR,yyline,yychar,yytext());
            } 
            // fall through
          case 114: break;
          case 46: 
            { TokenInfo token = new TokenInfo(yytext(), "TRUE", yyline, yychar);  tokens.add(token); return new Symbol(sym.TRUE,yyline,yychar,yytext());
            } 
            // fall through
          case 115: break;
          case 47: 
            { TokenInfo token = new TokenInfo(yytext(), "ELSE", yyline, yychar);  tokens.add(token); return new Symbol(sym.ELSE,yyline,yychar,yytext());
            } 
            // fall through
          case 116: break;
          case 48: 
            { TokenInfo token = new TokenInfo(yytext(), "FIND", yyline, yychar);  tokens.add(token); return new Symbol(sym.FIND,yyline,yychar,yytext());
            } 
            // fall through
          case 117: break;
          case 49: 
            { TokenInfo token = new TokenInfo(yytext(), "LIST", yyline, yychar);  tokens.add(token); return new Symbol(sym.LIST,yyline,yychar,yytext());
            } 
            // fall through
          case 118: break;
          case 50: 
            { TokenInfo token = new TokenInfo(yytext(), "BOOL", yyline, yychar);  tokens.add(token); return new Symbol(sym.BOOL,yyline,yychar,yytext());
            } 
            // fall through
          case 119: break;
          case 51: 
            { TokenInfo token = new TokenInfo(yytext(), "CHAR", yyline, yychar);  tokens.add(token); return new Symbol(sym.CHAR,yyline,yychar,yytext());
            } 
            // fall through
          case 120: break;
          case 52: 
            { TokenInfo token = new TokenInfo(yytext(), "VOID", yyline, yychar);  tokens.add(token); return new Symbol(sym.VOID,yyline,yychar,yytext());
            } 
            // fall through
          case 121: break;
          case 53: 
            { TokenInfo token = new TokenInfo(yytext(), "ROUND", yyline, yychar);  tokens.add(token); return new Symbol(sym.ROUND,yyline,yychar,yytext());
            } 
            // fall through
          case 122: break;
          case 54: 
            { TokenInfo token = new TokenInfo(yytext(), "FALSE", yyline, yychar);  tokens.add(token); return new Symbol(sym.FALSE,yyline,yychar,yytext());
            } 
            // fall through
          case 123: break;
          case 55: 
            { TokenInfo token = new TokenInfo(yytext(), "BREAK", yyline, yychar);  tokens.add(token); return new Symbol(sym.BREAK,yyline,yychar,yytext());
            } 
            // fall through
          case 124: break;
          case 56: 
            { TokenInfo token = new TokenInfo(yytext(), "CONST", yyline, yychar);  tokens.add(token); return new Symbol(sym.CONST,yyline,yychar,yytext());
            } 
            // fall through
          case 125: break;
          case 57: 
            { TokenInfo token = new TokenInfo(yytext(), "MATCH", yyline, yychar);  tokens.add(token); return new Symbol(sym.MATCH,yyline,yychar,yytext());
            } 
            // fall through
          case 126: break;
          case 58: 
            { TokenInfo token = new TokenInfo(yytext(), "WHILE", yyline, yychar);  tokens.add(token); return new Symbol(sym.WHILE,yyline,yychar,yytext());
            } 
            // fall through
          case 127: break;
          case 59: 
            { TokenInfo token = new TokenInfo(yytext(), "RETURN", yyline, yychar);  tokens.add(token); return new Symbol(sym.RETURN,yyline,yychar,yytext());
            } 
            // fall through
          case 128: break;
          case 60: 
            { TokenInfo token = new TokenInfo(yytext(), "REMOVE", yyline, yychar);  tokens.add(token); return new Symbol(sym.REMOVE,yyline,yychar,yytext());
            } 
            // fall through
          case 129: break;
          case 61: 
            { TokenInfo token = new TokenInfo(yytext(), "APPEND", yyline, yychar);  tokens.add(token); return new Symbol(sym.APPEND,yyline,yychar,yytext());
            } 
            // fall through
          case 130: break;
          case 62: 
            { TokenInfo token = new TokenInfo(yytext(), "LENGTH", yyline, yychar);  tokens.add(token); return new Symbol(sym.LENGTH,yyline,yychar,yytext());
            } 
            // fall through
          case 131: break;
          case 63: 
            { TokenInfo token = new TokenInfo(yytext(), "STRUCT", yyline, yychar);  tokens.add(token); return new Symbol(sym.STRUCT,yyline,yychar,yytext());
            } 
            // fall through
          case 132: break;
          case 64: 
            { TokenInfo token = new TokenInfo(yytext(), "STRING", yyline, yychar);  tokens.add(token); return new Symbol(sym.STRING,yyline,yychar,yytext());
            } 
            // fall through
          case 133: break;
          case 65: 
            { TokenInfo token = new TokenInfo(yytext(), "DOUBLE", yyline, yychar);  tokens.add(token); return new Symbol(sym.DOUBLE,yyline,yychar,yytext());
            } 
            // fall through
          case 134: break;
          case 66: 
            { TokenInfo token = new TokenInfo(yytext(), "PRINTLN", yyline, yychar);  tokens.add(token); return new Symbol(sym.PRINTLN,yyline,yychar,yytext());
            } 
            // fall through
          case 135: break;
          case 67: 
            { TokenInfo token = new TokenInfo(yytext(), "TOSTRING", yyline, yychar);  tokens.add(token); return new Symbol(sym.TOSTRING,yyline,yychar,yytext());
            } 
            // fall through
          case 136: break;
          case 68: 
            { TokenInfo token = new TokenInfo(yytext(), "CONTINUE", yyline, yychar);  tokens.add(token); return new Symbol(sym.CONTINUE,yyline,yychar,yytext());
            } 
            // fall through
          case 137: break;
          case 69: 
            { TokenInfo token = new TokenInfo(yytext(), "START_WITH", yyline, yychar);  tokens.add(token); return new Symbol(sym.START_WITH,yyline,yychar,yytext());
            } 
            // fall through
          case 138: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
