
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PT = 7;
  public static final int PAR_DER = 4;
  public static final int NUMERO = 24;
  public static final int Y = 47;
  public static final int X = 46;
  public static final int RES = 29;
  public static final int CHAR_ARRAY = 26;
  public static final int DOUBLE = 23;
  public static final int PIE = 41;
  public static final int COR_DER = 11;
  public static final int TITULOY = 49;
  public static final int TITULOX = 48;
  public static final int BAR = 40;
  public static final int COLUMN = 39;
  public static final int ARROBA = 16;
  public static final int TITULO = 45;
  public static final int DIV = 31;
  public static final int ASIGNA = 14;
  public static final int MIN = 38;
  public static final int LLAV_IZQ = 5;
  public static final int ID = 22;
  public static final int MEDIANA = 34;
  public static final int EOF = 0;
  public static final int DOS_PT = 8;
  public static final int error = 1;
  public static final int PROGRAM = 17;
  public static final int MUL = 30;
  public static final int COMA = 9;
  public static final int CADENA = 21;
  public static final int VALUES = 50;
  public static final int LINE = 42;
  public static final int MODA = 35;
  public static final int MOD = 32;
  public static final int PAR_IZQ = 3;
  public static final int INICIALIZACION = 15;
  public static final int ASIGNACION = 12;
  public static final int ACCESO = 13;
  public static final int COR_IZQ = 10;
  public static final int VARIANZA = 36;
  public static final int END = 18;
  public static final int SUM = 28;
  public static final int PTCOMA = 2;
  public static final int ARR = 27;
  public static final int MEDIA = 33;
  public static final int LLAV_DER = 6;
  public static final int EXEC = 44;
  public static final int LABEL = 51;
  public static final int MAX = 37;
  public static final int HISTOGRAM = 43;
  public static final int VAR = 25;
  public static final int PRINT = 20;
  public static final int CONSOLE = 19;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PTCOMA",
  "PAR_IZQ",
  "PAR_DER",
  "LLAV_IZQ",
  "LLAV_DER",
  "PT",
  "DOS_PT",
  "COMA",
  "COR_IZQ",
  "COR_DER",
  "ASIGNACION",
  "ACCESO",
  "ASIGNA",
  "INICIALIZACION",
  "ARROBA",
  "PROGRAM",
  "END",
  "CONSOLE",
  "PRINT",
  "CADENA",
  "ID",
  "DOUBLE",
  "NUMERO",
  "VAR",
  "CHAR_ARRAY",
  "ARR",
  "SUM",
  "RES",
  "MUL",
  "DIV",
  "MOD",
  "MEDIA",
  "MEDIANA",
  "MODA",
  "VARIANZA",
  "MAX",
  "MIN",
  "COLUMN",
  "BAR",
  "PIE",
  "LINE",
  "HISTOGRAM",
  "EXEC",
  "TITULO",
  "X",
  "Y",
  "TITULOX",
  "TITULOY",
  "VALUES",
  "LABEL"
  };
}

